### ISSUE TITLE
Java_com_adcolony_sdk_ADCVMModule_00024ADCJSVirtualMachine_update Crash

### ISSUE THREAD

**Issue by shaniamjad** [AdColony/AdColony-iOS-SDK-3#27]
I have integrated Adcolony 3.1.2 SDK into my Cocos2dx Android project.. I have also integrated Crashlytics SDK, on which i am getting a crash related to your SDK and its being faced by lots of my users. So could you please investigate this issue and fix it please. Thanks. 

Cocos2dx Version: 3.15.1
Adcolony SDK: 3.1.2 (gradle)
Crashlog: [crashlog-1.txt](https://github.com/AdColony/AdColony-iOS-SDK-3/files/1213892/crashlog-1.txt)

**Comment by cmanibog-ac** [comment]
@shaniamjad I've reached out to our Engineering team for additional guidance on this crash. We'll follow up with more information or additional questions after reviewing these details.

**Comment by akwkong** [comment]
In the crashlog you sent, it looks like the device is running low on memory since it shows that RAM Free is only 2.9%. We have seen these crashes happen when RAM is low. Does Crashlytics also show these crashes happening on devices running low on memory?

**Comment by shaniamjad** [comment]
No unfortunately crashlytics doesn't tells us if this is a low memory crash OR other.. I have seen other similar crash and some of them were having 10% Free Ram which is more then enough i believe. So are you sure that this crash is occurring because of low memory?

**Comment by shaniamjad** [comment]
Hello guys, Is there any progress on this? Have you investigated this?

**Comment by rizwangaminations** [comment]
hi,
I am having same Issue as shaniamjad has reported.
are you guys are working on a fix or is there any work around to resolve this issue?

**Comment by akwkong** [comment]
We released version 3.2.1 of our Android SDK that should help with this crash. Could you give that a try and see if things have improved?

**Comment by shaniamjad** [comment]
Sure, Let me try that.. I will update you once i have it.

**Comment by rizwangaminations** [comment]
Great, 
let me update my app.

thanks anyway.

**Comment by rizwangaminations** [comment]
@akwkong hi,
i am still getting same issue, even after i updated SDK to adcolony:3.2.1
![screen shot 2017-10-05 at 11 04 55 am](https://user-images.githubusercontent.com/31472835/31212965-3acfae24-a9bd-11e7-8fb0-6a72b10abc91.png)
could you please investigate this issue?

**Comment by AwaisQmar** [comment]
Hi @akwkong !
I'm also having the same issue.
I'm using newly updated SDK adcolony:3.2.1

Crashlytics Report is as following:

cocos2dx-3.15.1
OS Version: 6.0.1
Device: Galaxy J7
Disk Free: 50%

0  memtrack.exynos5.so            0xf73bd72e strlcpy
1  memtrack.exynos5.so            0xef0080c1 Java_com_adcolony_sdk_ADCVMModule_00024ADCJSVirtualMachine_update
2  gralloc.exynos5.so             0xe2126a0d oatexec

**Comment by AwaisQmar** [comment]
Hi @akwkong !
Any update on this crash ?

**Comment by AwaisQmar** [comment]
@akwkong !
any update regarding this crash ?

**Comment by DevJ0049** [comment]
i have same issue
